import {
  Database,
  LineChart,
  Search,
  PenTool,
  MapPin,
  Brain,
  Megaphone,
  ShieldCheck,
  TrendingUp,
  Users,
  FileText,
  Laptop,
  Home,
  Wind,
  DollarSign,
  Presentation,
  Zap,
  Star,
} from "lucide-react";

export const iconMap: Record<string, React.ElementType> = {
  database: Database,
  chart: LineChart,
  search: Search,
  pen: PenTool,
  map: MapPin,
  brain: Brain,
  megaphone: Megaphone,
  shield: ShieldCheck,
  trending: TrendingUp,
  users: Users,
  file: FileText,
  laptop: Laptop,
  home: Home,
  wind: Wind,
  dollar: DollarSign,
  presentation: Presentation,
  zap: Zap,
  star: Star,
};

export function getServiceIcon(slug: string): React.ElementType {
  const slugMap: Record<string, React.ElementType> = {
    "crm-data-cleanup-service": Database,
    "llm-seo-optimization-service": Search,
    "quickbooks-desktop-migration-service": DollarSign,
    "linkedin-ghostwriting-service": PenTool,
    "google-business-profile-optimization-service": MapPin,
    "ai-prompt-engineering-service": Brain,
    "landing-page-production-service": Presentation,
    "ai-ad-production-testing-service": Megaphone,
    "senior-tech-support-subscription": Laptop,
    "flat-fee-financial-coaching-service": DollarSign,
    "hyperlocal-air-quality-monitoring-service": Wind,
    "alcohol-free-corporate-wellness-service": ShieldCheck,
    "first-100-customers-launch-agency": TrendingUp,
    "regulatory-monitoring-service": FileText,
    "ai-accelerated-mvp-development-service": Zap,
    "family-business-exit-coaching-service": Users,
    "founder-retreat-service": Star,
    "smart-home-environmental-monitoring-service": Home,
  };
  return slugMap[slug] ?? Star;
}
